# Generated by Django 4.2 on 2024-06-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_alter_service_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="comments",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)s_comments",
                to="services.servicecomment",
            ),
        ),
    ]
