# Generated by Django 4.2 on 2024-06-28 21:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("storage", "0001_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("overview", models.CharField(max_length=512)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("responsible", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("C", "Completed"),
                            ("I", "Ongoing"),
                            ("P", "Planned"),
                            ("S", "Stalled"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("is_new", models.BooleanField(default=True)),
                ("slug", models.SlugField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "album",
                    models.ManyToManyField(
                        related_name="%(app_label)s_%(class)s_album",
                        to="storage.mediamodel",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_manager",
                        to="members.member",
                    ),
                ),
                (
                    "picture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_picture",
                        to="storage.mediamodel",
                    ),
                ),
            ],
        ),
    ]
