# Generated by Django 4.2 on 2024-07-16 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebsiteConfig",
        ),
    ]
