services:
  db:
    image: postgres:16.1
    container_name: postgres-hive
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DEFAULT_DATABASE_USER}
      POSTGRES_PASSWORD: ${DEFAULT_DATABASE_PASSWORD}
      POSTGRES_DB: ${DEFAULT_DATABASE_NAME}
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2.5
    container_name: hive-redis
    ports:
      - "127.0.0.1:6379:6379"

  django:
    build:
      context: ../../back
      dockerfile: build/Dockerfile
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    env_file:
      - .env
    container_name: django-hive
    environment:
      - STAGE=production
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  nuxt-app:
    build:
      context: ../../hive-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data:
  static_volume:
  media_volume:
