# Generated by Django 4.2 on 2024-07-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="open_ai_thread_id",
            field=models.CharField(default="x", max_length=128),
            preserve_default=False,
        ),
    ]
